version: '3.8'

services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    volumes:
      - ./gateway:/app
    environment:
      - NODE_ENV=development
    
  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
    volumes:
      - ./auth-service:/app
    environment:
      - NODE_ENV=development
      - PORT=4000
      - JWT_SECRET=supersecret

  profile-service:
    build: ./profile-service
    ports:
      - "5001:5000"
    volumes:
      - ./profile-service:/app
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=supersecret
