name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (API Gateway)
        working-directory: gateway
        run: npm install

      - name: Run Lint
        working-directory: gateway
        run: npm run lint || echo "Linting issues need addressing."

      - name: Run Tests
        working-directory: gateway
        run: npm test || echo "No tests configured yet."

      - name: Build (if applicable)
        working-directory: gateway
        run: npm run build || echo "Build step skipped in development."
